# -*- coding: utf-8 -*-
"""P2_BasicCalculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YgAWB2xVdme9BpByc7lByDAjNkNe-pTe
"""

#This is a Basic Calculator on Python
a = 0
b = 0

while True:
  try:
    print('Hi ^^, Please Type First Number')
    a = float(input())
    break
  except: print('Invalid Input')


while True:
  try:
    print('Second number')
    b = float(input())
    break
  except: print('Invalid Input')

while True:

  print('What do you wanna do today? ')
  print('Type +, -, *, /, finish')
  op = input()
  if op == '+':
    print(a+b)
  elif op == '-':
    print(a-b)
  elif op == '*':
    print(a*b)
  elif op == '/':
    if b == 0:
      print('Cannot Divide by zero')
    else:
      print(a/b)
  elif op == 'finish':
    print('Bye ^^')
    break
  else:
    print('Invalid Operation')
    continue