# -*- coding: utf-8 -*-
"""P1_GreetingMachine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HYz0bFTSIbt2vFSVYzK-KHQyM6ibKw_T
"""

#This Program says Hello and asks for my name

print('Hello World! ^^')
print('What is your name? ') #ask for their name
MyName = input()

print('It is good to meet you, ' +MyName)
print('The lenght of your name is: ')
print(len(MyName))
print('What is your age? ')
MyAge = input()
cant = 5
if (cant==1):
  y=  'year'
else:
  y = 'years'

print('You will be '+str(int(MyAge)+ cant)+' in ' +str(int(cant))+' '+y)